//
// credits by TeamRandom
//

using System;
using Styx.Common;
using System.Windows.Forms;
using System.IO;
using Styx.WoWInternals;
using System.Collections.Generic;
using Styx.Helpers;

namespace PokehbuddyLogicCreator
{
    public partial class PetBattle
    {
        public static PetBattleSettings PetSettings;
        public static string ReadActiveSlot()
        {
            List<string> cnt = Lua.GetReturnValues("dummy={} for i = 1, 3   do  local petID= C_PetJournal.GetPetLoadOutInfo(i); dummy[i]=petID  end return tonumber(dummy[C_PetBattles.GetActivePet(1)],16);");
            //Logging.Write(cnt[0]);
            //int decAgain = int.Parse(, System.Globalization.NumberStyles.HexNumber);
            return cnt[0];//decAgain.ToString();

        }

        public static string GetNameByID(string thepetID)
        {
            Lua.DoString("C_PetJournal.SetFlagFilter(LE_PET_JOURNAL_FLAG_FAVORITES, false) C_PetJournal.SetFlagFilter(LE_PET_JOURNAL_FLAG_COLLECTED, true) C_PetJournal.SetFlagFilter(LE_PET_JOURNAL_FLAG_NOT_COLLECTED, true) ");
            Lua.DoString("C_PetJournal.ClearSearchFilter() C_PetJournal.AddAllPetSourcesFilter() C_PetJournal.AddAllPetTypesFilter() ");
            ////Lua.DoString("C_PetJournal.SetSearchFilter('" + petname + "')");

            List<string> cnt = Lua.GetReturnValues("local dummy='' for i=1,C_PetJournal.GetNumPets(false) do     local petID, speciesID, isOwned, customName, level, favorite, isRevoked, name, icon, petType  = C_PetJournal.GetPetInfoByIndex(i, false)  if tonumber(petID,16) == " + thepetID + " then dummy=name ; end end return dummy;");

            if (cnt[0] != null && cnt[0] != "")
            {



                return cnt[0];
            }
            return "Error";
        }

        public static void LoadPetSettings(string petID, string speciesID)
        {

            string filename = Application.StartupPath + "\\Plugins\\Pokehbuddy\\PetSettings\\" + petID + ".xml";
            if (!File.Exists(filename))
            {

                string filename2 = Application.StartupPath + "\\Plugins\\Pokehbuddy\\PetSettings\\" + GetNameByID(petID) + ".xml";
                if (File.Exists(filename2))
                {
                    File.Copy(filename2, filename);
                }
            }

            try
            {
                PetSettings = new PetBattleSettings(filename);


            }
            catch (Exception ex) { Logging.WriteException(ex); }
            PetSettings.Logic = ConvertFromOldFile(PetSettings.Logic);
            PetSettings.Save();
        }

        public static void LoadPetSettingsBN(string petID)
        {

            string filename = Application.StartupPath + "\\Plugins\\Pokehbuddy\\PetSettings\\" + petID + ".xml";


            try
            {
                PetSettings = new PetBattleSettings(filename);


            }
            catch (Exception ex) { Logging.WriteException(ex); }
            PetSettings.Logic = ConvertFromOldFile(PetSettings.Logic);
            PetSettings.Save();
        }

        public static string GetNameBySpeciesID(string speciesID)
        {

            for (int i = 0; i < allpetz.Length; i++)
            {
                if (allpetz[i] == speciesID) return allpetz[i + 1];

            }
            return "Error";
        }

        public static string GetSpeciesByName(string speciesID)
        {

            for (int i = 0; i < allpetz.Length; i++)
            {
                if (allpetz[i] == speciesID) return allpetz[i - 1];

            }
            return "Error";
        }

        public static string ReadActiveSlotSpecies()
        {
            List<string> cnt = Lua.GetReturnValues("local petID = C_PetJournal.GetPetLoadOutInfo(1); local speciesID = C_PetJournal.GetPetInfoByPetID(petID) return speciesID");
            //Logging.Write(cnt[0]);
            //int decAgain = int.Parse(, System.Globalization.NumberStyles.HexNumber);
            //return cnt[0];//decAgain.ToString();
            for (int i = 0; i < allpetz.Length; i++)
            {
                if (allpetz[i] == cnt[0]) return allpetz[i + 1];
            }
            return "";

        }



        #region Pet Data
        private static string[] allpetz = new string[] {"1147","Harbinger of Flame",@"INTERFACE\ICONS\ABILITY_SEARINGARROW.BLP",
"120","Winter's Little Helper",@"INTERFACE\ICONS\INV_HOLIDAY_CHRISTMAS_PRESENT_01.BLP",
"255","Celestial Dragon",@"INTERFACE\ICONS\INV_PET_CELESTIALDRAGON.BLP",
"243","Onyxian Whelpling",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_BLACK.BLP",
"489","Spawn of Onyxia",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_BLACK.BLP",
"195","White Tickbird Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_OWL.BLP",
"187","Vampiric Batling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_BAT.BLP",
"1156","Mini Mindslayer",@"INTERFACE\ICONS\INV_QIRAJIDOL_ALABASTER.BLP",
"244","Core Hound Pup",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_COREHOUND.BLP",
"270","Dark Phoenix Hatchling",@"INTERFACE\ICONS\INV_MISC_DARKPHOENIXPET_01.BLP",
"175","Phoenix Hatchling",@"INTERFACE\ICONS\INV_MISC_PHEONIXPET_01.BLP",
"162","Sinister Squashling",@"INTERFACE\ICONS\INV_MISC_FOOD_59.BLP",
"202","Baby Blizzard Bear",@"INTERFACE\ICONS\INV_PET_BABYBLIZZARDBEAR.BLP",
"319","Feline Familiar",@"INTERFACE\ICONS\ACHIEVEMENT_HALLOWEEN_CAT_01.BLP",
"277","Clockwork Gnome",@"INTERFACE\ICONS\INV_MISC_HEAD_CLOCKWORKGNOME_01.BLP",
"285","Landro's Lil' XT",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_XT002DECONSTRUCTOR_01.BLP",
"472","Rabid Nut Varmint 5000",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"225","Curious Oracle Hatchling",@"INTERFACE\ICONS\ACHIEVEMENT_REPUTATION_MURLOCORACLE.BLP",
"226","Curious Wolvar Pup",@"INTERFACE\ICONS\ACHIEVEMENT_REPUTATION_WOLVAR.BLP",
"119","Father Winter's Helper",@"INTERFACE\ICONS\INV_HOLIDAY_CHRISTMAS_PRESENT_03.BLP",
"329","Murkablo",@"INTERFACE\ICONS\INV_PET_DIABLOBABYMURLOC.BLP",
"122","Peddlefeet",@"INTERFACE\ICONS\INV_AMMO_ARROW_02.BLP",
"120","Winter's Little Helper",@"INTERFACE\ICONS\INV_HOLIDAY_CHRISTMAS_PRESENT_01.BLP",
"145","Blue Dragonhawk Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_DRAGONHAWK.BLP",
"142","Golden Dragonhawk Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_DRAGONHAWK.BLP",
"320","Lil' Tarecgosa",@"INTERFACE\ICONS\INV_MISC_PETDRAGONWHELPTARECGOSA.BLP",
"557","Nether Faerie Dragon",@"INTERFACE\ICONS\INV_EGG_06.BLP",
"196","Proto-Drake Whelp",@"INTERFACE\ICONS\ABILITY_MOUNT_DRAKE_PROTO.BLP",
"143","Red Dragonhawk Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_DRAGONHAWK.BLP",
"144","Silver Dragonhawk Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_DRAGONHAWK.BLP",
"179","Spirit of Competition",@"INTERFACE\ICONS\INV_JEWELRY_AMULET_03.BLP",
"52","Ancona Chicken",@"INTERFACE\ICONS\SPELL_MAGIC_POLYMORPHCHICKEN.BLP",
"259","Blue Mini Jouster",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_DRAGONHAWK.BLP",
"138","Blue Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"325","Brilliant Kaliri",@"INTERFACE\ICONS\INV_FEATHER_13.BLP",
"646","Chicken",@"INTERFACE\ICONS\INV_THANKSGIVING_TURKEY.BLP",
"146","Firefly",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WASP.BLP",
"521","Fledgling Nether Ray",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_NETHERRAY.BLP",
"478","Forest Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"260","Gold Mini Jouster",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_VULTURE.BLP",
"68","Great Horned Owl",@"INTERFACE\ICONS\ABILITY_EYEOFTHEOWL.BLP",
"50","Green Wing Macaw",@"INTERFACE\ICONS\INV_FEATHER_12.BLP",
"311","Guardian Cub",@"INTERFACE\ICONS\INV_PET_WINGEDLION.BLP",
"67","Hawk Owl",@"INTERFACE\ICONS\ABILITY_EYEOFTHEOWL.BLP",
"149","Miniwing",@"INTERFACE\ICONS\INV_BOX_BIRDCAGE_01.BLP",
"186","Nether Ray Fry",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_NETHERRAY.BLP",
"309","Pterrordax Hatchling",@"INTERFACE\ICONS\INV_MISC_ARCHAEOLOGY_BABYPTERRODAX.BLP",
"139","Red Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"51","Senegal",@"INTERFACE\ICONS\INV_FEATHER_11.BLP",
"498","Tainted Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"194","Tickbird Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_OWL.BLP",
"167","Tiny Sporebat",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPOREBAT.BLP",
"84","Westfall Chicken",@"INTERFACE\ICONS\SPELL_MAGIC_POLYMORPHCHICKEN.BLP",
"141","White Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"195","White Tickbird Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_OWL.BLP",
"140","Yellow Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"321","Creepy Crate",@"INTERFACE\ICONS\INV_CRATE_02.BLP",
"266","Fossilized Hatchling",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TINYDINOSAURSKELETON.BLP",
"302","Landro's Lichling",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_KELTHUZAD_01.BLP",
"218","Sen'jin Fetish",@"INTERFACE\ICONS\INV_MISC_COIN_15.BLP",
"187","Vampiric Batling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_BAT.BLP",
"310","Voodoo Figurine",@"INTERFACE\ICONS\INV_MISC_ARCHAEOLOGY_TROLLGOLEM.BLP",
"272","Armadillo Pup",@"INTERFACE\ICONS\INV_MISC_BABYARMADILLOPET.BLP",
"706","Bandicoon",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"707","Bandicoon Kit",@"INTERFACE\ICONS\INV_PET_RACCOON.BLP",
"406","Beetle",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"137","Brown Rabbit",@"INTERFACE\ICONS\INV_CRATE_02.BLP",
"468","Creepy Crawly",@"INTERFACE\ICONS\INV_MISC_AHNQIRAJTRINKET_01.BLP",
"467","Dung Beetle",@"INTERFACE\ICONS\INV_MISC_AHNQIRAJTRINKET_01.BLP",
"158","Egbert",@"INTERFACE\ICONS\INV_PET_EGBERT.BLP",
"479","Elfin Rabbit",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"209","Elwynn Lamb",@"INTERFACE\ICONS\SPELL_NATURE_POLYMORPH.BLP",
"193","Giant Sewer Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"448","Hare",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"203","Little Fawn",@"INTERFACE\ICONS\INV_PET_FAWN.BLP",
"708","Malayan Quillrat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"709","Malayan Quillrat Pup",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"710","Marsh Fiddler",@"INTERFACE\ICONS\INV_PET_CRICKET.BLP",
"633","Mountain Skunk",@"INTERFACE\ICONS\INV_MISC_VOLATILESHADOW.BLP",
"210","Mulgore Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_TALLSTRIDER.BLP",
"323","Nuts",@"INTERFACE\ICONS\INV_MISC_FOOD_02.BLP",
"159","Peanut",@"INTERFACE\ICONS\INV_PET_BABY_ELEKK_GRAY.BLP",
"250","Perky Pug",@"INTERFACE\ICONS\INV_MISC_BONE_01.BLP",
"166","Pint-Sized Pink Pachyderm",@"INTERFACE\ICONS\INV_PET_BABY_ELEKK_RED.BLP",
"386","Prairie Dog",@"INTERFACE\ICONS\INV_PET_PRAIRIEDOG.BLP",
"378","Rabbit",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"417","Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"424","Roach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"717","Savory Beetle",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"512","Scarab Hatchling",@"INTERFACE\ICONS\INV_MISC_AHNQIRAJTRINKET_01.BLP",
"289","Scooter the Snail",@"INTERFACE\ICONS\INV_MISC_SHELL_04.BLP",
"397","Skunk",@"INTERFACE\ICONS\INV_MISC_VOLATILESHADOW.BLP",
"200","Spring Rabbit",@"INTERFACE\ICONS\INV_MISC_FOOD_54.BLP",
"379","Squirrel",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"160","Stinker",@"INTERFACE\ICONS\INV_BOX_PETCARRIER_01.BLP",
"485","Stone Armadillo",@"INTERFACE\ICONS\INV_MISC_BABYARMADILLOPET.BLP",
"497","Tainted Cockroach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"499","Tainted Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"55","Undercity Cockroach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"127","Whiskers the Rat",@"INTERFACE\ICONS\INV_PET_RATCAGE.BLP",
"118","Winter Reindeer",@"INTERFACE\ICONS\INV_MISC_BELL_01.BLP",
"153","Wolpertinger",@"INTERFACE\ICONS\INV_DRINK_13.BLP",
"267","Enchanted Lantern",@"INTERFACE\ICONS\INV_MISC_LANTERN_01.BLP",
"342","Festival Lantern",@"INTERFACE\ICONS\INV_SHIELD_26.BLP",
"308","Legs",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_THEBLACKSTALKER.BLP",
"136","Mana Wyrmling",@"INTERFACE\ICONS\SPELL_NATURE_ABOLISHMAGIC.BLP",
"157","Willy",@"INTERFACE\ICONS\INV_PET_SLEEPYWILLY.BLP",
"212","Ammen Vale Lashling",@"INTERFACE\ICONS\INV_MISC_FLOWER_04.BLP",
"293","Elementium Geode",@"INTERFACE\ICONS\INV_MISC_ARCHSTONE_01.BLP",
"253","Frigid Frostling",@"INTERFACE\ICONS\SPELL_FROST_FROZENCORE.BLP",
"199","Kirin Tor Familiar",@"INTERFACE\ICONS\ABILITY_CREATURE_DISEASE_05.BLP",
"337","Lumpy",@"INTERFACE\ICONS\INV_ORE_TIN_01.BLP",
"291","Singing Sunflower",@"INTERFACE\ICONS\INV_MISC_FLOWER_02.BLP",
"162","Sinister Squashling",@"INTERFACE\ICONS\INV_MISC_FOOD_59.BLP",
"128","Spirit of Summer",@"INTERFACE\ICONS\INV_POTION_33.BLP",
"204","Teldrassil Sproutling",@"INTERFACE\ICONS\INV_MISC_HERB_03.BLP",
"279","Tiny Shale Spider",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_03.BLP",
"117","Tiny Snowman",@"INTERFACE\ICONS\INV_PET_SNOWMAN.BLP",
"220","Withers",@"INTERFACE\ICONS\ABILITY_DRUID_FORCEOFNATURE.BLP",
"635","Adder",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"74","Albino Snake",@"INTERFACE\ICONS\SPELL_NATURE_GUARDIANWARD.BLP",
"632","Ash Lizard",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"75","Black Kingsnake",@"INTERFACE\ICONS\SPELL_NATURE_GUARDIANWARD.BLP",
"40","Bombay Cat",@"INTERFACE\ICONS\INV_PET_CATS_BOMBAYCAT.BLP",
"77","Brown Snake",@"INTERFACE\ICONS\SPELL_NATURE_GUARDIANWARD.BLP",
"224","Calico Cat",@"INTERFACE\ICONS\INV_PET_CATS_CALICOCAT.BLP",
"197","Cobra Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_COBRASTRIKES.BLP",
"488","Coral Snake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"41","Cornish Rex Cat",@"INTERFACE\ICONS\INV_PET_CATS_CORNISHREXCAT.BLP",
"78","Crimson Snake",@"INTERFACE\ICONS\SPELL_NATURE_GUARDIANWARD.BLP",
"343","Darkmoon Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_JUNGLETIGER.BLP",
"330","Darkmoon Monkey",@"INTERFACE\ICONS\ABILITY_HUNTER_ASPECTOFTHEMONKEY.BLP",
"232","Darting Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RAPTOR.BLP",
"484","Desert Spider",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"233","Deviate Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RAPTOR.BLP",
"205","Dun Morogh Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_POLARBEAR_BLACK.BLP",
"631","Emerald Boa",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"319","Feline Familiar",@"INTERFACE\ICONS\ACHIEVEMENT_HALLOWEEN_CAT_01.BLP",
"475","Giraffe Calf",@"INTERFACE\ICONS\ABILITY_WARSTOMP.BLP",
"235","Leaping Hatchling",@"INTERFACE\ICONS\ABILITY_MOUNT_RAPTOR.BLP",
"450","Maggot",@"INTERFACE\ICONS\INV_MISC_FOOD_VENDOR_BOILEDSILKWORMPUPA.BLP",
"236","Obsidian Hatchling",@"INTERFACE\ICONS\ABILITY_MOUNT_RAPTOR.BLP",
"43","Orange Tabby Cat",@"INTERFACE\ICONS\INV_PET_CATS_ORANGETABBYCAT.BLP",
"301","Panther Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_BLACKPANTHER.BLP",
"237","Ravasaur Hatchling",@"INTERFACE\ICONS\ABILITY_MOUNT_RAPTOR.BLP",
"238","Razormaw Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RAPTOR.BLP",
"239","Razzashi Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RAPTOR.BLP",
"482","Rock Viper",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"414","Scorpid",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SCORPID.BLP",
"44","Siamese Cat",@"INTERFACE\ICONS\INV_PET_CATS_SIAMESECAT.BLP",
"511","Sidewinder",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"45","Silver Tabby Cat",@"INTERFACE\ICONS\INV_PET_CATS_SILVERTABBYCAT.BLP",
"90","Smolderweb Hatchling",@"INTERFACE\ICONS\INV_BOX_BIRDCAGE_01.BLP",
"387","Snake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"412","Spider",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"433","Spiky Lizard",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"466","Spiny Lizard",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"432","Stripe-Tailed Scorpid",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SCORPID.BLP",
"405","Tree Python",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"506","Venomspitter Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"517","Warpstalker Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WARPSTALKER.BLP",
"418","Water Snake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"306","Winterspring Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_PINKTIGER.BLP",
"89","Worg Pup",@"INTERFACE\ICONS\INV_BOX_PETCARRIER_01.BLP",
"335","Darkmoon Turtle",@"INTERFACE\ICONS\INV_PET_SPEEDY.BLP",
"383","Eternal Strider",@"INTERFACE\ICONS\INV_PET_WATERSTRIDER.BLP",
"847","Fishy",@"INTERFACE\ICONS\INV_MISC_FISH_58.BLP",
"495","Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"483","Horny Toad",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"132","Magical Crawdad",@"INTERFACE\ICONS\INV_MISC_FISH_14.BLP",
"165","Mojo",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"192","Mr. Chilly",@"INTERFACE\ICONS\INV_MISC_PENGUINPET.BLP",
"164","Muckbreath",@"INTERFACE\ICONS\INV_PET_BABYCROCODILE_MUCHBREATH.BLP",
"198","Pengu",@"INTERFACE\ICONS\INV_PET_BABYPENGU.BLP",
"340","Sea Pony",@"INTERFACE\ICONS\ABILITY_MOUNT_SEAHORSE.BLP",
"711","Sifang Otter",@"INTERFACE\ICONS\INV_PET_OTTER.BLP",
"419","Small Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"713","Softshell Snapling",@"INTERFACE\ICONS\INV_PET_SPEEDY.BLP",
"125","Speedy",@"INTERFACE\ICONS\INV_PET_SPEEDY.BLP",
"401","Strand Crab",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"211","Strand Crawler",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"420","Toad",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"65","Tree Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"64","Wood Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"752","Yellow-Bellied Bullfrog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"254","Blue Clockwork Rocket Bot",@"INTERFACE\ICONS\INV_GIZMO_06.BLP",
"191","Clockwork Rocket Bot",@"INTERFACE\ICONS\INV_GIZMO_06.BLP",
"338","Darkmoon Tonk",@"INTERFACE\ICONS\INV_GIZMO_GOBLINGTONKCONTROLLER.BLP",
"339","Darkmoon Zeppelin",@"INTERFACE\ICONS\INV_MISC_TOY_05.BLP",
"262","De-Weaponized Mechanical Companion",@"INTERFACE\ICONS\INV_PET_DEWEAONIZEDMECHCOMPANION.BLP",
"95","Lifelike Toad",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"86","Lil' Smoky",@"INTERFACE\ICONS\INV_PET_LILSMOKY.BLP",
"256","Lil' XT",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_XT002DECONSTRUCTOR_01.BLP",
"83","Mechanical Chicken",@"INTERFACE\ICONS\INV_PET_MECHANICALCHICKEN.BLP",
"39","Mechanical Squirrel",@"INTERFACE\ICONS\INV_PET_MECHANICALSQUIRREL.BLP",
"215","Mechanopeep",@"INTERFACE\ICONS\ABILITY_MOUNT_MECHASTRIDER.BLP",
"261","Personal World Destroyer",@"INTERFACE\ICONS\INV_MISC_ENGGIZMOS_03.BLP",
"85","Pet Bombling",@"INTERFACE\ICONS\INV_MISC_BOMB_04.BLP",
"471","Robo-Chick",@"INTERFACE\ICONS\INV_PET_MECHANICALCHICKEN.BLP",
"116","Tranquil Mechanical Yeti",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_GORILLA.BLP",
"216","Argent Gruntling",@"INTERFACE\ICONS\ACHIEVEMENT_REPUTATION_ARGENTCHAMPION.BLP",
"336","Darkmoon Balloon",@"INTERFACE\ICONS\INV_MISC_BALLOON_01.BLP",
"283","Guild Herald",@"INTERFACE\ICONS\ACHIEVEMENT_GUILDPERK_HONORABLEMENTION_RANK2.BLP",
"281","Guild Page",@"INTERFACE\ICONS\ACHIEVEMENT_GUILDPERK_HONORABLEMENTION.BLP",
"332","Horde Balloon",@"INTERFACE\ICONS\INV_MISC_BALLOON_02.BLP",
"1155","Anubisath Idol",@"INTERFACE\ICONS\INV_QIRAJIDOL_STRIFE.BLP",
"214","Argent Squire",@"INTERFACE\ICONS\ACHIEVEMENT_REPUTATION_ARGENTCHAMPION.BLP",
"1149","Corefire Imp",@"INTERFACE\ICONS\SPELL_SHADOW_SUMMONIMP.BLP",
"294","Deathy",@"INTERFACE\ICONS\INV_DRAGONWHELPCATACLYSM.BLP",
"821","Feral Vermling",@"INTERFACE\ICONS\INV_PET_VERMIN.BLP",
"514","Flayer Youngling",@"INTERFACE\ICONS\ABILITY_RACIAL_FLAYER.BLP",
"333","Gregarious Grell",@"INTERFACE\ICONS\SPELL_SHADOW_SUMMONIMP.BLP",
"228","Grunty",@"INTERFACE\ICONS\INV_PET_GRUNTY.BLP",
"282","Guild Herald",@"INTERFACE\ICONS\ACHIEVEMENT_GUILDPERK_HONORABLEMENTION_RANK2.BLP",
"280","Guild Page",@"INTERFACE\ICONS\ACHIEVEMENT_GUILDPERK_HONORABLEMENTION.BLP",
"121","Gurky",@"INTERFACE\ICONS\INV_PET_BABYMURLOCS_PINK.BLP",
"1157","Harpy Youngling",@"INTERFACE\ICONS\INV_FEATHER_08.BLP",
"835","Hopling",@"INTERFACE\ICONS\ACHIEVEMENT_BREWERY_1.BLP",
"1166","Kun-Lai Runt",@"INTERFACE\ICONS\ABILITY_DRUID_SWIPE.BLP",
"111","Lurky",@"INTERFACE\ICONS\INV_PET_BABYMURLOCS_WHITE.BLP",
"189","Mini Tyrael",@"INTERFACE\ICONS\INV_SWORD_07.BLP",
"298","Moonkin Hatchling",@"INTERFACE\ICONS\INV_MISC_PETMOONKINTA.BLP",
"296","Moonkin Hatchling",@"INTERFACE\ICONS\INV_MISC_PETMOONKINNE.BLP",
"1168","Murki",@"INTERFACE\ICONS\INV_EGG_03.BLP",
"217","Murkimus the Gladiator",@"INTERFACE\ICONS\INV_SPEAR_05.BLP",
"107","Murky",@"INTERFACE\ICONS\INV_PET_BABYMURLOCS_BLUE.BLP",
"248","Pandaren Monk",@"INTERFACE\ICONS\INV_MISC_PET_03.BLP",
"513","Qiraji Guardling",@"INTERFACE\ICONS\ACHIEVEMENT_ZONE_SILITHUS_01.BLP",
"515","Sporeling Sprout",@"INTERFACE\ICONS\INV_MUSHROOM_11.BLP",
"1158","Stunted Yeti",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_SHRIVELEDMONKEYPAW.BLP",
"1073","Terky",@"INTERFACE\ICONS\INV_PET_BABYMURLOCS_WHITE.BLP",
"57","Azure Whelpling",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_BLUE.BLP",
"1152","Chrominius",@"INTERFACE\ICONS\INV_MISC_RUBYSANCTUM1.BLP",
"58","Crimson Whelpling",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_RED.BLP",
"56","Dark Whelpling",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_BLACK.BLP",
"1153","Death Talon Whelpguard",@"INTERFACE\ICONS\ACHIEVEMENT_DUNGEON_COABLACKDRAGONFLIGHT_HEROIC.BLP",
"1167","Emerald Proto-Whelp",@"INTERFACE\ICONS\ABILITY_MOUNT_FELDRAKE.BLP",
"59","Emerald Whelpling",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_GREEN.BLP",
"180","Essence of Competition",@"INTERFACE\ICONS\INV_JEWELRY_TALISMAN_10.BLP",
"1161","Infinite Whelpling",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_INFINITECORRUPTOR.BLP",
"268","Lil' Deathwing",@"INTERFACE\ICONS\INV_DRAGONWHELPCATACLYSM.BLP",
"131","Netherwhelp",@"INTERFACE\ICONS\INV_NETHERWHELP.BLP",
"1165","Nexus Whelpling",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_MALYGOS_01.BLP",
"347","Soul of the Aspects",@"INTERFACE\ICONS\INV_PET_CHROMATICDRAGON.BLP",
"87","Sprite Darter Hatchling",@"INTERFACE\ICONS\INV_PET_SPRITE_DARTER_HATCHLING.BLP",
"802","Thundering Serpent Hatchling",@"INTERFACE\ICONS\INV_PET_BABYCLOUDSERPENT.BLP",
"757","Tiny Green Dragon",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_GREEN.BLP",
"758","Tiny Red Dragon",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_GREEN.BLP",
"1151","Untamed Hatchling",@"INTERFACE\ICONS\ACHIEVEMENT_DUNGEON_COABLACKDRAGONFLIGHT.BLP",
"819","Wild Crimson Hatchling",@"INTERFACE\ICONS\INV_PANDARENSERPENTPET.BLP",
"818","Wild Golden Hatchling",@"INTERFACE\ICONS\INV_PET_BABYCLOUDSERPENT_GOLD.BLP",
"817","Wild Jade Hatchling",@"INTERFACE\ICONS\INV_PET_BABYCLOUDSERPENT.BLP",
"331","Alliance Balloon",@"INTERFACE\ICONS\INV_MISC_BALLOON_04.BLP",
"732","Amber Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"626","Bat",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_BAT.BLP",
"316","Cenarion Hatchling",@"INTERFACE\ICONS\INV_EGG_02.BLP",
"849","Chi-ji Kite",@"INTERFACE\ICONS\ABILITY_MOUNT_PANDARENKITEMOUNT.BLP",
"47","Cockatiel",@"INTERFACE\ICONS\INV_FEATHER_08.BLP",
"507","Crested Owl",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_OWL.BLP",
"421","Crimson Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"1068","Crow",@"INTERFACE\ICONS\ABILITY_HUNTER_MURDEROFCROWS.BLP",
"1062","Darkmoon Glowfly",@"INTERFACE\ICONS\SPELL_FIRE_FELFLAMERING.BLP",
"169","Dragon Kite",@"INTERFACE\ICONS\INV_MISC_DRAGONKITE_02.BLP",
"537","Dragonbone Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_VULTURE.BLP",
"747","Effervescent Glowfly",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WASP.BLP",
"395","Fledgling Buzzard",@"INTERFACE\ICONS\SPELL_HUNTER_ASPECTOFTHEHAWK.BLP",
"756","Fungal Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"753","Garden Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"748","Gilded Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"630","Gilnean Raven",@"INTERFACE\ICONS\INV_FEATHER_02.BLP",
"464","Grey Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"245","Gryphon Hatchling",@"INTERFACE\ICONS\INV_MISC_PET_02.BLP",
"645","Highlands Turkey",@"INTERFACE\ICONS\INV_THANKSGIVING_TURKEY.BLP",
"130","Hippogryph Hatchling",@"INTERFACE\ICONS\INV_EGG_02.BLP",
"49","Hyacinth Macaw",@"INTERFACE\ICONS\INV_FEATHER_08.BLP",
"534","Imperial Eagle Chick",@"INTERFACE\ICONS\ABILITY_HUNTER_EAGLEEYE.BLP",
"1039","Imperial Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"792","Jade Crane Chick",@"INTERFACE\ICONS\INV_PET_BABYCRANE.BLP",
"718","Luyu Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"722","Mei Li Sparkler",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WASP.BLP",
"544","Oasis Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"403","Parrot",@"INTERFACE\ICONS\SPELL_NATURE_FORCEOFNATURE.BLP",
"201","Plump Turkey",@"INTERFACE\ICONS\INV_THANKSGIVING_TURKEY.BLP",
"409","Polly",@"INTERFACE\ICONS\SPELL_NATURE_FORCEOFNATURE.BLP",
"271","Rustberg Gull",@"INTERFACE\ICONS\INV_MISC_SEAGULLPET_01.BLP",
"573","Sandy Petrel",@"INTERFACE\ICONS\INV_MISC_SEAGULLPET_01.BLP",
"560","Sea Gull",@"INTERFACE\ICONS\INV_MISC_SEAGULLPET_01.BLP",
"754","Shrine Fly",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WASP.BLP",
"503","Silky Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"69","Snowy Owl",@"INTERFACE\ICONS\ABILITY_EYEOFTHEOWL.BLP",
"402","Swamp Moth",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_MOTH.BLP",
"728","Szechuan Chicken",@"INTERFACE\ICONS\INV_THANKSGIVING_TURKEY.BLP",
"287","Tiny Flamefly",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG06.BLP",
"206","Tirisfal Batling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_BAT.BLP",
"525","Turkey",@"INTERFACE\ICONS\INV_THANKSGIVING_TURKEY.BLP",
"241","Tuskarr Kite",@"INTERFACE\ICONS\INV_MISC_PET_01.BLP",
"548","Wildhammer Gryphon Hatchling",@"INTERFACE\ICONS\INV_MISC_PET_02.BLP",
"850","Yu'lon Kite",@"INTERFACE\ICONS\INV_MISC_DRAGONKITE_04.BLP",
"456","Blighthawk",@"INTERFACE\ICONS\INV_PET_UNDEADEAGLE.BLP",
"264","Crawling Claw",@"INTERFACE\ICONS\INV_OFFHAND_STRATHOLME_A_02.BLP",
"348","Eye of the Legion",@"INTERFACE\ICONS\SPELL_SHADOW_EVILEYE.BLP",
"346","Fetish Shaman",@"INTERFACE\ICONS\INV_SPEAR_05.BLP",
"188","Frosty",@"INTERFACE\ICONS\INV_PET_FROSTWYRM.BLP",
"1144","Fungal Abomination",@"INTERFACE\ICONS\SPELL_DRUID_WILDMUSHROOM_FRENZY.BLP",
"190","Ghostly Skull",@"INTERFACE\ICONS\INV_MISC_BONE_HUMANSKULL_01.BLP",
"1143","Giant Bone Spider",@"INTERFACE\ICONS\INV_QIRAJIDOL_DEATH.BLP",
"628","Infected Fawn",@"INTERFACE\ICONS\ABILITY_CREATURE_POISON_02.BLP",
"627","Infected Squirrel",@"INTERFACE\ICONS\INV_PET_DISEASEDSQUIRREL.BLP",
"453","Infested Bear Cub",@"INTERFACE\ICONS\INV_PET_DISEASEDBEARCUB.BLP",
"249","Lil' K.T.",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_KELTHUZAD_01.BLP",
"458","Lost of Lordaeron",@"INTERFACE\ICONS\ACHIEVEMENT_HALLOWEEN_GHOST_01.BLP",
"1145","Mr. Bigglesworth",@"INTERFACE\ICONS\INV_PET_CATS_SIAMESECAT.BLP",
"439","Restless Shadeling",@"INTERFACE\ICONS\ABILITY_DRUID_DREAMSTATE.BLP",
"538","Scourged Whelpling",@"INTERFACE\ICONS\INV_MISC_HEAD_DRAGON_BLACK.BLP",
"463","Spirit Crab",@"INTERFACE\ICONS\INV_JEWELCRAFTING_TRUESILVERCRAB.BLP",
"1146","Stitched Pup",@"INTERFACE\ICONS\INV_MISC_BONE_01.BLP",
"487","Alpine Chipmunk",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"441","Alpine Hare",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"641","Arctic Hare",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"374","Black Lamb",@"INTERFACE\ICONS\SPELL_NATURE_POLYMORPH.BLP",
"398","Black Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"455","Blighted Squirrel",@"INTERFACE\ICONS\INV_PET_DISEASEDSQUIRREL.BLP",
"639","Borean Marmot",@"INTERFACE\ICONS\INV_PET_PRAIRIEDOG.BLP",
"449","Brown Marmot",@"INTERFACE\ICONS\INV_PET_PRAIRIEDOG.BLP",
"70","Brown Prairie Dog",@"INTERFACE\ICONS\INV_PET_PRAIRIEDOG.BLP",
"540","Carrion Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"393","Cockroach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"556","Crystal Beetle",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"1061","Darkmoon Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_TALLSTRIDER.BLP",
"848","Darkmoon Rabbit",@"INTERFACE\ICONS\INV_JEWELCRAFTING_CRIMSONHARE.BLP",
"755","Death's Head Cockroach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"555","Deepholm Cockroach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"447","Fawn",@"INTERFACE\ICONS\INV_PET_FAWN.BLP",
"415","Fire Beetle",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"541","Fire-Proof Roach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"644","Fjord Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"477","Gazelle Fawn",@"INTERFACE\ICONS\ABILITY_WARSTOMP.BLP",
"430","Gold Beetle",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"170","Golden Pig",@"INTERFACE\ICONS\INV_MISC_COIN_01.BLP",
"733","Grassland Hopper",@"INTERFACE\ICONS\INV_PET_CRICKET.BLP",
"443","Grasslands Cottontail",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"647","Grizzly Squirrel",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"539","Grotto Vole",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"550","Highlands Mouse",@"INTERFACE\ICONS\INV_PET_MOUSE.BLP",
"823","Highlands Skunk",@"INTERFACE\ICONS\INV_MISC_VOLATILESHADOW.BLP",
"1040","Imperial Silkworm",@"INTERFACE\ICONS\INV_PET_MAGGOT.BLP",
"442","Irradiated Roach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"429","Lava Beetle",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"543","Locust",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"404","Long-tailed Mole",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"155","Lucky",@"INTERFACE\ICONS\INV_MISC_ELVENCOINS.BLP",
"671","Lucky Quilen Cub",@"INTERFACE\ICONS\INV_QUILINPET.BLP",
"570","Masked Tanuki",@"INTERFACE\ICONS\INV_PET_RACCOON.BLP",
"703","Masked Tanuki Pup",@"INTERFACE\ICONS\INV_PET_RACCOON.BLP",
"391","Mountain Cottontail",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"385","Mouse",@"INTERFACE\ICONS\INV_PET_MOUSE.BLP",
"126","Mr. Wiggles",@"INTERFACE\ICONS\INV_BELT_25.BLP",
"638","Nether Roach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"381","Porcupette",@"INTERFACE\ICONS\INV_PET_PORCUPINE.BLP",
"727","Prairie Mouse",@"INTERFACE\ICONS\INV_PET_MOUSE.BLP",
"743","Rapana Whelk",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_FOSSIL_SNAILSHELL.BLP",
"1042","Red Cricket",@"INTERFACE\ICONS\INV_PET_CRICKET.BLP",
"452","Red-Tailed Chipmunk",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_01.BLP",
"392","Redridge Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"744","Resilient Roach",@"INTERFACE\ICONS\INV_PET_COCKROACH.BLP",
"496","Rusty Snail",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_FOSSIL_SNAILSHELL.BLP",
"665","Sand Scarab",@"INTERFACE\ICONS\INV_SCARAB_CLAY.BLP",
"493","Shimmershell Snail",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_FOSSIL_SNAILSHELL.BLP",
"677","Shy Bandicoon",@"INTERFACE\ICONS\INV_PET_RACCOON.BLP",
"568","Silkbead Snail",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_FOSSIL_SNAILSHELL.BLP",
"171","Silver Pig",@"INTERFACE\ICONS\INV_MISC_COIN_03.BLP",
"820","Singing Cricket",@"INTERFACE\ICONS\INV_PET_CRICKET.BLP",
"640","Snowshoe Hare",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"72","Snowshoe Rabbit",@"INTERFACE\ICONS\INV_CRATE_02.BLP",
"492","Stinkbug",@"INTERFACE\ICONS\INV_INSCRIPTION_PIGMENT_BUG04.BLP",
"675","Stormwind Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"553","Stowaway Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"546","Tol'vir Scarab",@"INTERFACE\ICONS\INV_SCARAB_STONE.BLP",
"729","Tolai Hare",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"730","Tolai Hare Pup",@"INTERFACE\ICONS\INV_MISC_RABBIT.BLP",
"469","Twilight Beetle",@"INTERFACE\ICONS\INV_MISC_AHNQIRAJTRINKET_01.BLP",
"454","Undercity Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"410","Wharf Rat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"740","Yakrat",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_03.BLP",
"549","Yellow-Bellied Marmot",@"INTERFACE\ICONS\INV_PET_PRAIRIEDOG.BLP",
"1160","Arcane Eye",@"INTERFACE\ICONS\INV_MISC_RUNE_03.BLP",
"903","Baneling",@"INTERFACE\ICONS\ABILITY_PET_BANELING.BLP",
"1063","Darkmoon Eye",@"INTERFACE\ICONS\SPELL_SHADOW_EVILEYE.BLP",
"114","Disgusting Oozeling",@"INTERFACE\ICONS\ABILITY_CREATURE_POISON_05.BLP",
"213","Enchanted Broom",@"INTERFACE\ICONS\INV_PET_BROOM.BLP",
"183","Ethereal Soul-Trader",@"INTERFACE\ICONS\SPELL_NATURE_GROUNDINGTOTEM.BLP",
"446","Jade Oozeling",@"INTERFACE\ICONS\INV_MISC_SLIME_01.BLP",
"845","Jade Owl",@"INTERFACE\ICONS\INV_JEWELCRAFTING_JADEOWL.BLP",
"231","Jade Tiger",@"INTERFACE\ICONS\INV_MISC_GEM_STONE_01.BLP",
"1159","Lofty Libram",@"INTERFACE\ICONS\INV_MISC_BOOK_08.BLP",
"341","Lunar Lantern",@"INTERFACE\ICONS\INV_SHIELD_26.BLP",
"292","Magic Lamp",@"INTERFACE\ICONS\INV_SHIELD_26.BLP",
"500","Minfernal",@"INTERFACE\ICONS\SPELL_SHADOW_SUMMONINFERNAL.BLP",
"93","Mini Diablo",@"INTERFACE\ICONS\INV_DIABLOSTONE.BLP",
"547","Nordrassil Wisp",@"INTERFACE\ICONS\SPELL_NATURE_WISPSPLODE.BLP",
"530","Oily Slimeling",@"INTERFACE\ICONS\INV_MISC_SLIME_02.BLP",
"240","Onyx Panther",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_05.BLP",
"229","Shimmering Wyrmling",@"INTERFACE\ICONS\INV_ELEMENTAL_PRIMAL_MANA.BLP",
"1127","Spectral Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_SPECTRALTIGER.BLP",
"242","Spectral Tiger Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_SPECTRALTIGER.BLP",
"251","Toxic Wasteling",@"INTERFACE\ICONS\INV_MISC_SLIME_01.BLP",
"552","Twilight Fiendling",@"INTERFACE\ICONS\SPELL_SHADOW_SHADOWFIEND.BLP",
"1154","Viscidus Globule",@"INTERFACE\ICONS\ABILITY_CREATURE_POISON_06.BLP",
"94","Zergling",@"INTERFACE\ICONS\SPELL_SHADOW_SUMMONFELHUNTER.BLP",
"247","Zipao Tiger",@"INTERFACE\ICONS\INV_JEWELCRAFTING_GEM_06.BLP",
"838","Amethyst Shale Hatchling",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_05.BLP",
"1150","Ashstone Core",@"INTERFACE\ICONS\INV_ELEMENTAL_ETERNAL_SHADOW.BLP",
"1117","Cinder Kitten",@"INTERFACE\ICONS\INV_MISC_FIREKITTY.BLP",
"559","Crimson Geode",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_02.BLP",
"318","Crimson Lasher",@"INTERFACE\ICONS\INV_MISC_FLOWER_04.BLP",
"554","Crimson Shale Hatchling",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_02.BLP",
"837","Emerald Shale Hatchling",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_03.BLP",
"519","Fel Flame",@"INTERFACE\ICONS\SPELL_FIRE_FELFIRE.BLP",
"834","Grinder",@"INTERFACE\ICONS\INV_MISC_REFORGEDARCHSTONE_01.BLP",
"856","Jade Tentacle",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_YOGGSARON_01.BLP",
"423","Lava Crab",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"297","Lil' Ragnaros",@"INTERFACE\ICONS\ACHIEVEMENT_BOSS_RAGNAROS.BLP",
"1125","Pandaren Air Spirit",@"INTERFACE\ICONS\INV_PET_PANDARENELEMENTAL_AIR.BLP",
"1126","Pandaren Earth Spirit",@"INTERFACE\ICONS\INV_PET_PANDARENELEMENTAL_EARTH.BLP",
"1124","Pandaren Fire Spirit",@"INTERFACE\ICONS\INV_PET_PANDARENELEMENTAL_FIRE.BLP",
"868","Pandaren Water Spirit",@"INTERFACE\ICONS\INV_PET_PANDARENELEMENTAL.BLP",
"265","Pebble",@"INTERFACE\ICONS\SPELL_NATURE_EARTHELEMENTAL_TOTEM.BLP",
"460","Ruby Sapling",@"INTERFACE\ICONS\ABILITY_DRUID_FORCEOFNATURE.BLP",
"846","Sapphire Cub",@"INTERFACE\ICONS\INV_JEWELCRAFTING_BLACKPEARLPANTHER.BLP",
"172","Searing Scorchling",@"INTERFACE\ICONS\INV_PET_SCORCHEDSTONE.BLP",
"650","Terrible Turnip",@"INTERFACE\ICONS\INV_PET_TURNIPPET.BLP",
"509","Tiny Bog Beast",@"INTERFACE\ICONS\INV_SHOULDER_18.BLP",
"445","Tiny Twister",@"INTERFACE\ICONS\ABILITY_DRUID_GALEWINDS.BLP",
"480","Topaz Shale Hatchling",@"INTERFACE\ICONS\INV_MISC_QIRAJICRYSTAL_04.BLP",
"855","Venus",@"INTERFACE\ICONS\INV_MISC_LIFEBLOOD.BLP",
"535","Water Waveling",@"INTERFACE\ICONS\SPELL_FROST_SUMMONWATERELEMENTAL_2.BLP",
"724","Alpine Foxling",@"INTERFACE\ICONS\INV_MISC_FOXKIT.BLP",
"725","Alpine Foxling Kit",@"INTERFACE\ICONS\INV_MISC_FOXKIT.BLP",
"716","Amethyst Spiderling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"558","Arctic Fox Kit",@"INTERFACE\ICONS\INV_MISC_FOXKIT.BLP",
"427","Ash Spiderling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"425","Ash Viper",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"411","Baby Ape",@"INTERFACE\ICONS\INV_PET_ACHIEVEMENT_WINAPETBATTLE.BLP",
"156","Bananas",@"INTERFACE\ICONS\INV_MISC_FOOD_24.BLP",
"42","Black Tabby Cat",@"INTERFACE\ICONS\INV_PET_CATS_BLACKTABBYCAT.BLP",
"380","Bucktooth Flapper",@"INTERFACE\ICONS\INV_PET_BEAVER.BLP",
"459","Cat",@"INTERFACE\ICONS\ABILITY_HUNTER_CATLIKEREFLEXES.BLP",
"474","Cheetah Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_JUNGLETIGER.BLP",
"518","Clefthoof Runt",@"INTERFACE\ICONS\INV_MISC_FOOT_CENTAUR.BLP",
"742","Clouded Hedgehog",@"INTERFACE\ICONS\INV_PET_PORCUPINE.BLP",
"562","Coral Adder",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"745","Crunchy Scorpion",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SCORPID.BLP",
"634","Crystal Spider",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"508","Darkshore Cub",@"INTERFACE\ICONS\INV_MISC_BEARCUBBROWN.BLP",
"523","Devouring Maggot",@"INTERFACE\ICONS\INV_QIRAJ_SKINSANDWORM.BLP",
"504","Diemetradon Hatchling",@"INTERFACE\ICONS\INV_MISC_MONSTERSCALES_16.BLP",
"207","Durotar Scorpion",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SCORPID.BLP",
"396","Dusk Spiderling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"457","Festering Maggot",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WORM.BLP",
"714","Feverbite Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"529","Fjord Worg Pup",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_WOLF.BLP",
"407","Forest Spiderling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"278","Fox Kit",@"INTERFACE\ICONS\INV_MISC_FOXKIT.BLP",
"571","Grove Viper",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"234","Gundrak Hatchling",@"INTERFACE\ICONS\ABILITY_MOUNT_RAPTOR.BLP",
"851","Horned Lizard",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"317","Hyjal Bear Cub",@"INTERFACE\ICONS\INV_MISC_BEARCUBBROWN.BLP",
"699","Jumping Spider",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"678","Jungle Grub",@"INTERFACE\ICONS\INV_PET_MAGGOT.BLP",
"438","King Snake",@"INTERFACE\ICONS\SPELL_NATURE_GUARDIANWARD.BLP",
"461","Larva",@"INTERFACE\ICONS\INV_MISC_FOOD_VENDOR_BOILEDSILKWORMPUPA.BLP",
"307","Lashtail Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RAPTOR.BLP",
"545","Leopard Scorpid",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SCORPID.BLP",
"437","Little Black Ram",@"INTERFACE\ICONS\ABILITY_MOUNT_MOUNTAINRAM.BLP",
"408","Lizard Hatchling",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"422","Moccasin",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"428","Molten Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"286","Mr. Grubbs",@"INTERFACE\ICONS\INV_PET_MAGGOT.BLP",
"303","Nightsaber Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_JUNGLETIGER.BLP",
"92","Panda Cub",@"INTERFACE\ICONS\INV_BELT_05.BLP",
"726","Plains Monitor",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"124","Poley",@"INTERFACE\ICONS\INV_BELT_09.BLP",
"399","Rat Snake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"431","Rattlesnake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"465","Ravager Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RAVAGER.BLP",
"491","Sand Kitten",@"INTERFACE\ICONS\ABILITY_HUNTER_CATLIKEREFLEXES.BLP",
"528","Scalded Basilisk Hatchling",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"416","Scorpling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SCORPID.BLP",
"741","Silent Hedgehog",@"INTERFACE\ICONS\INV_PET_PORCUPINE.BLP",
"494","Silithid Hatchling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SILITHID.BLP",
"637","Skittering Cavern Crawler",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"440","Snow Cub",@"INTERFACE\ICONS\ABILITY_MOUNT_PINKTIGER.BLP",
"532","Stunted Shardhorn",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_RHINO.BLP",
"679","Summit Kid",@"INTERFACE\ICONS\INV_MISC_MONSTERHORN_02.BLP",
"1128","Sumprush Rodent",@"INTERFACE\ICONS\INV_PET_BEAVER.BLP",
"567","Temple Snake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"505","Twilight Iguana",@"INTERFACE\ICONS\TRADE_ARCHAEOLOGY_TROLLLIZARDFOOTCHARM.BLP",
"470","Twilight Spider",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"46","White Kitten",@"INTERFACE\ICONS\INV_PET_CATS_WHITEKITTEN.BLP",
"400","Widow Spiderling",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_SPIDER.BLP",
"246","Wind Rider Cub",@"INTERFACE\ICONS\INV_MISC_PET_04.BLP",
"731","Zooey Snake",@"INTERFACE\ICONS\ABILITY_HUNTER_SNAKETRAP.BLP",
"836","Aqua Strider",@"INTERFACE\ICONS\INV_MISC_FLUTE_01.BLP",
"649","Biletoad",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"174","Chuck",@"INTERFACE\ICONS\INV_PET_BABYCROCODILE_CHUCK.BLP",
"751","Dancing Water Skimmer",@"INTERFACE\ICONS\INV_PET_WATERSTRIDER.BLP",
"564","Emerald Turtle",@"INTERFACE\ICONS\INV_MISC_FISH_TURTLE_02.BLP",
"746","Emperor Crab",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"569","Garden Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"749","Golden Civet",@"INTERFACE\ICONS\INV_PET_OTTER.BLP",
"750","Golden Civet Kitten",@"INTERFACE\ICONS\INV_PET_OTTER.BLP",
"648","Huge Toad",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"106","Jubling",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"565","Jungle Darter",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"680","Kuitan Mongoose",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_07.BLP",
"702","Leopard Tree Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"542","Mac Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"566","Mirror Strider",@"INTERFACE\ICONS\INV_PET_WATERSTRIDER.BLP",
"737","Mongoose",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_07.BLP",
"739","Mongoose Pup",@"INTERFACE\ICONS\INV_MISC_MONSTERTAIL_07.BLP",
"328","Purple Puffer",@"INTERFACE\ICONS\INV_MISC_FISH_34.BLP",
"388","Shore Crab",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"629","Shore Crawler",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"712","Sifang Otter Pup",@"INTERFACE\ICONS\INV_PET_OTTER.BLP",
"173","Snarly",@"INTERFACE\ICONS\INV_PET_BABYCROCODILE_SNARLY.BLP",
"723","Spiny Terrapin",@"INTERFACE\ICONS\ABILITY_MOUNT_PANDARANMOUNTEPICBLACK.BLP",
"572","Spirebound Crab",@"INTERFACE\ICONS\ABILITY_HUNTER_PET_CRAB.BLP",
"502","Spotted Bell Frog",@"INTERFACE\ICONS\SPELL_SHAMAN_HEX.BLP",
"652","Tiny Goldfish",@"INTERFACE\ICONS\INV_MISC_FISH_36.BLP",
"163","Toothy",@"INTERFACE\ICONS\INV_PET_BABYCROCODILE_TOOTHY.BLP",
"536","Tundra Penguin",@"INTERFACE\ICONS\INV_PET_BABYPENGU.BLP",
"473","Turquoise Turtle",@"INTERFACE\ICONS\INV_MISC_FISH_TURTLE_02.BLP",
"1013","Wanderer's Festival Hatchling",@"INTERFACE\ICONS\ABILITY_MOUNT_PANDARANMOUNTBLACK.BLP",
"1163","Anodized Robo Cub",@"INTERFACE\ICONS\INV_PET_MECHANICALBEARCUB.BLP",
"1142","Clock'em",@"INTERFACE\ICONS\INV_MISC_HEAD_CLOCKWORKGNOME_01.BLP",
"1164","Cogblade Raptor",@"INTERFACE\ICONS\INV_PET_MECHANICALRAPTORPET.BLP",
"1162","Fluxfire Feline",@"INTERFACE\ICONS\INV_PET_MECHANICALTIGERCUB.BLP",
"844","Mechanical Pandaren Dragonling",@"INTERFACE\ICONS\ACHIEVEMENT_DUNGEON_COABLACKDRAGONFLIGHT_NORMAL.BLP",
"258","Mini Thor",@"INTERFACE\ICONS\T_ROBOTICON.BLP",
"168","Rocket Chicken",@"INTERFACE\ICONS\INV_MISC_ENGGIZMOS_ROCKETCHICKEN.BLP",
"389","Tiny Harvester",@"INTERFACE\ICONS\INV_MISC_GEAR_03.BLP"};
        #endregion
    }

    /***********************************************************\
    *															*
    *				Settings part!!								*
    *															*
    \***********************************************************/

    public class PetBattleSettings : Settings
    {
        public PetBattleSettings(string settingsPath)
            : base(settingsPath)
        {
            Load();
        }

        [Setting, DefaultValue("SWAPOUT Health(THISPET) ISLESSTHAN 30@PASSTURN HASBUFF(822) EQUALS true@CASTSPELL(1) COOLDOWN(SKILL(1)) EQUALS false")]
        public string Logic { get; set; }

    }
}