//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by the tool。
//     运行时版本:4.0.30319.269
//
//     Changes to this file may result in incorrect behaviour and if
//     Re-generate the code and these changes will be lost。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleGrindZone.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class for finding localised strings etc.。
    /// </summary>
    // This category is made up of StronglyTypedResourceBuilder
    // class by means of a class similar to ResGen or Visual Studio automatically generated by the tool。
    // To add or remove a member, edit .ResX file, then re-run the ResGen
    // (with /str As a command option)，or regenerate VS Projects。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cache of such used ResourceManager Examples。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleGrindZone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Use this strongly typed resource class to find for all resources
        ///   Rewrite the current thread's CurrentUICulture Properties。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
