//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by the tool。
//     Runtime version:4.0.30319.269
//
//     Changes to this document may result in incorrect behaviour，and if
//     Re-generate the code and these changes will be lost。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleGrindZone.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
